;::Send {Blind}q
,::Send {Blind}w
.::Send {Blind}e
p::Send {Blind}r
y::Send {Blind}t
f::Send {Blind}y
g::Send {Blind}u
c::Send {Blind}i
r::Send {Blind}o
l::Send {Blind}p
a::Send {Blind}a
o::Send {Blind}s
e::Send {Blind}d
u::Send {Blind}f
i::Send {Blind}g
d::Send {Blind}h
h::Send {Blind}j
t::Send {Blind}k
n::Send {Blind}l
s::Send {Blind};
'::Send {Blind}z
q::Send {Blind}x
j::Send {Blind}c
k::Send {Blind}v
x::Send {Blind}b
b::Send {Blind}n
m::Send {Blind}m
w::Send {Blind},
v::Send {Blind}.
z::Send {Blind}/